# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{radiant-settings-extension}
  s.version = "1.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Alex Wayne", "Jim Gay"]
  s.date = %q{2010-07-05}
  s.description = %q{Allows users to edit the details of the config table.}
  s.email = %q{jim@saturnflyer.com}
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    ".gitignore",
     "HELP_admin.md",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "app/controllers/admin/settings_controller.rb",
     "app/helpers/admin/settings_helper.rb",
     "app/views/admin/settings/_setting.html.haml",
     "app/views/admin/settings/edit.html.haml",
     "app/views/admin/settings/index.html.haml",
     "app/views/admin/settings/new.html.haml",
     "config/locales/en.yml",
     "config/routes.rb",
     "cucumber.yml",
     "db/migrate/001_add_description_to_config.rb",
     "db/migrate/002_add_settings_roles.rb",
     "features/support/env.rb",
     "features/support/paths.rb",
     "lib/config_find_all_as_tree.rb",
     "lib/config_protection.rb",
     "lib/settings_tags.rb",
     "lib/tasks/settings_extension_tasks.rake",
     "public/images/.DS_Store",
     "public/images/admin/.DS_Store",
     "public/images/admin/setting.png",
     "settings_extension.rb",
     "spec/controllers/admin/settings_controller_spec.rb",
     "spec/helpers/admin/settings_helper_spec.rb",
     "spec/lib/radiant/admin_ui_spec.rb",
     "spec/lib/settings_tags_spec.rb",
     "spec/models/config_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/views/admin/settings/edit_view_spec.rb",
     "spec/views/admin/settings/index_view_spec.rb"
  ]
  s.homepage = %q{http://github.com/saturnflyer/radiant-settings-extension}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Settings Extension for Radiant CMS}
  s.test_files = [
    "spec/controllers/admin/settings_controller_spec.rb",
     "spec/helpers/admin/settings_helper_spec.rb",
     "spec/lib/radiant/admin_ui_spec.rb",
     "spec/lib/settings_tags_spec.rb",
     "spec/models/config_spec.rb",
     "spec/spec_helper.rb",
     "spec/views/admin/settings/edit_view_spec.rb",
     "spec/views/admin/settings/index_view_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

